### ISSUE TITLE
Indexace mapy je nekompletní

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-aonline#13]
Při provedení `index_map` se zaindexuje pouze část záznamů ze souboru `AMCR_aklo_210916.csv`. Indexace se přitom tváří, že skončila úspěšně, zaindexuje se však pouze ca. 29 tis. záznamů z celkových 105 tis.

V souboru s daty žádnou zjevnou chybu nevidím - není tam nastaven nějaký time-out pro indexaci nebo něco takového?

**Comment by albertoh** [comment]
Soubor je nevalidni, ma nedokonce uvozovky.
 Napriklad "C-9123960A-K01" zni tak:
C-9123960A-K01#15.778251#50.233588#[C-9123960A-K01] SVOBODNÉ DVORY (HRADEC KRÁLOVÉ): RANÝ STŘEDOVĚK 2-4 - pohřební areál nesp. - orientační zjištění (v roce 1903 - )#651#1150#pohřební areál#pohřebiště/hřbitov#Dokumentovaný archeologický nález (typ vymezení: plocha; přesnost vymezení: odchylka desítky metrů)#Spolková cihelna".#https://digiarchiv.aiscr.cz/id/C-9123960A
Tam je neuzavrena uvozovka v poli Description_2:
 Spolková cihelna".
To zpusobi, je do indexu pro ten dokument do poli Description_2 se dostava vsechno dokud nenajdeme dalsi uvozovku, a presne:

"Spolková cihelna\".#https://digiarchiv.aiscr.cz/id/C-9123960A\nC-9123961A-K01#15.778251#50.233588#[C-9123961A-K01] SVOBODNÉ DVORY (HRADEC KRÁLOVÉ): únětická k. - pohřební areál nesp. - povrchový sběr (v roce 1908 - )#-2300#-1651#pohřební areál#pohřebiště/hřbitov#Dokumentovaný archeologický nález (typ vymezení: plocha; přesnost vymezení: odchylka desítky metrů)#Spollková cihelna.#https://digiarchiv.aiscr.cz/id/C-9123961A\nC-9123962A-K01#15.778251#50.233588#[C-9123962A-K01] SVOBODNÉ DVORY (HRADEC KRÁLOVÉ): RANÝ STŘEDOVĚK 2-4 - sídliště nesp. - povrchový sběr (v letech 1908 - 1910)#651#1150#sídliště#jiné#Dokumentovaný archeologický nález (typ vymezení: plocha; přesnost vymezení: odchylka desítky metrů)#Spolková cihelna\".",

To jsou nekolik zaznamu

**Comment by motyc** [comment]
Díky za informaci. Po pravdě mne problém z uvozovkami nenapadl, protože je ve zvoleném formátu CSV nepoužíváme pro označení textu (oddělovače jsou pouze hash). Nemá smysl to teď řešit na úrovni indexeru, prostě ty uvozovky odstraním z CSV, ale do budoucna se musíme domluvit, jak to má být správně.

**Comment by motyc** [comment]
Po odstranění uvozovek funguje v pořádku. Děkuji.
