### ISSUE TITLE
Nefunkční časová osa

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-aonline#15]
V mapě přestala fungovat časová osa (nejde pracovat s posuvníkem a ani změny v combo-boxech či textových polích nic nedělají). Ostatní filtry fungují.

https://aonline.aiscr.cz/map.vm

![image](https://user-images.githubusercontent.com/20186892/233070738-eb8c512d-2d1d-4eb6-9345-cf4b6a2f4385.png)

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Potvrzuji a zavírám.
