### ISSUE TITLE
Indexace se nezdařila

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-aonline#6]
Při pokusu o reindexaci došlo k chybě a data se nadaří zaindexovat. Pomohla až obnova celé aplikace ze zálohy.

**Comment by albertoh** [comment]
Zkusil jsem indexovat lokalne u sebe (stahl jsem si datove soubory ze serveru), a probehlo to v poradku, bez chyb.
 Jsou soubory v data adresar ty problemove?

**Comment by motyc** [comment]
Ne, jsou tam teď původní data. Spadlo to při indexaci souboru níže.
[AMCR_190919_aklo.zip](https://github.com/ARUP-CAS/aiscr-aonline/files/4245082/AMCR_190919_aklo.zip)

Pak už jsem to nezkoušel, neb obnova dala práci. Třeba to byla jen nějaká hloupá náhoda, ale zkus to prosím.

**Comment by albertoh** [comment]
Uz vidim problem. V tom csv jsou chybne souradnice nekterych dokument. Jsou tam hodnoty "pro.XXX"
Ale u mne indexace pokracovala, a indexovaly se dokumenty se spravnymi udaje. A nakonec chyba timeout pri pokusu udelat "optimize()" solru. Muzu komentovat ten radek, neni nutny.

**Comment by motyc** [comment]
Aha, omlouvám se tedy za chybu na své straně. On problém byl, že pak nešel zpětně indexovat ani ten původní soubor - celé se to nějak rozbilo. Zabrání tomu ta Tvá oprava? Pokud myslíš, že je to vhodné, pak to zakomentuj.

Ideální řešení by bylo, aby indexace chyby vypsala, abych se o nich nějak dozvěděl. To by možné bylo?

**Comment by albertoh** [comment]
Pridal jsem vystup indexace.

**Comment by motyc** [comment]
A je to už rovnou nasazené na produkci? Mohu tam tedy zkusit indexovat?

**Comment by albertoh** [comment]
Je to na 192.168.254.7

**Comment by motyc** [comment]
Opravil jsem soubor a zkusil znovu spustit indexaci. Zdá se mi, že se ale nice nestalo. Co dělám špatně?
![image](https://user-images.githubusercontent.com/20186892/75803237-6b8ebb00-5d7e-11ea-8a2a-487a059e73bd.png)

**Comment by albertoh** [comment]
Problem je zpusoben konfliktem mezi java verzemi.
Na serveru mame 8 a ja jsem u sebe testoval  s JDK 11.
Ted jsem zbuildoval znovu pod jdk8, pustil jsem indexace na server, a funguje to. Vysledek ma chyby typu:
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/arup: Exception writing document id C-201230215A-K01 to the index; possible analysis error

Ted jsou na serveru 98481 documentu

Myslim si, ze bylo by dobre zkoumat moznost povysit JDK

**Comment by motyc** [comment]
Tak to prosím udělej, teď jsem to zkoušel ještě jednou na všechny tři části a výsledek je, že v praxi a zdrojích úplně zmizel obsah, mapa přecijen něco vrátila. Teď jsou tím pádem rozbitá data na webu...

U zmíněného záznamu jinak v datech žádný problém nevidím :(

![image](https://user-images.githubusercontent.com/20186892/76441110-335f2c00-63bf-11ea-842a-e9e103e8b8d8.png)

http://www.archeologieonline.cz/
![image](https://user-images.githubusercontent.com/20186892/76441146-440fa200-63bf-11ea-97b6-dea118104e88.png)

**Comment by albertoh** [comment]
Opravil jsem indexy.
Ale problem je hlubsi. V SOLRu  jsem nasel nasledujici chyby:
java.lang.NoClassDefFoundError: Could not initialize class sun.nio.fs.LinuxNativeDispatcher

Vypada to, ze souvisi s JDK verzi. Jak probihaji aktualizace Javy? Automaticke? Zkoumam dal. Ale obavam se, ze budeme muset menit Javu, a/nebo vypnout automaticke aktualizace

**Comment by motyc** [comment]
@MichalKminek Prosím, tohle je otázka na Tebe - jak jsou řešeny aktualizace na serveru Archeologie Online? Prosím vykomunikujte to nějak s Albertem.

**Comment by albertoh** [comment]
Po restartu SOLRu, problem zmizel.
Asi bude potreba nejak hlidat to. Tj, pri aktualizaci javy, restartovat solr

**Comment by MichalKminek** [comment]
Vyjmul jsem java baliky z automaticke aktualizace.
