### ISSUE TITLE
Na titulní straně se vybrané záznamy zobrazují i duplicitně

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-aonline#8]
Příklad je tady:
![image](https://user-images.githubusercontent.com/20186892/97736516-1907c900-1adc-11eb-995a-e04b1e272799.png)

Prosím ošetřit tak, aby tam mohl být záznam vždy jen jednou.

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
V pořádku, díky za rychlé vyřízení.
